
export const UPDATE_LIST_VEHICLE = 'UPDATE_LIST_VEHICLE';


export const UPDATE_LIST_VEHICLE_TRENDING = 'UPDATE_LIST_VEHICLE_TRENDING';

export const UPDATE_LIST_VEHICLE_DEAL = 'UPDATE_LIST_VEHICLE_DEAL';